package io.github.thisccl.j4a.validation;

import java.io.IOException;
import java.nio.file.Path;

final class LocalJMeterSharedWorkerProtocolFixture {
    private LocalJMeterSharedWorkerProtocolFixture() {
    }

    static void create(Path jar) throws IOException {
        Path work = jar.getParent().resolve("shared-worker-protocol-src");
        String className = LocalJMeterValidationWorker.class.getName();
        Path source = work.resolve(className.replace('.', '/') + ".java");
        SyntheticPluginJarCompiler.writeSource(source, source());
        SyntheticPluginJarCompiler.compile(
                SyntheticPluginJarCompiler.compiler(),
                java.util.Collections.singletonList(source.toFile()),
                work.resolve("classes"));
        SyntheticPluginJarCompiler.writeJar(jar, work.resolve("classes"), className);
    }

    private static String source() {
        return "package io.github.thisccl.j4a.validation;\n"
                + "import java.io.*;\n"
                + "import java.lang.management.ManagementFactory;\n"
                + "import java.nio.charset.StandardCharsets;\n"
                + "import java.nio.file.*;\n"
                + "import java.util.Properties;\n"
                + "import java.util.HashSet;\n"
                + "import java.util.Set;\n"
                + "import java.util.concurrent.TimeUnit;\n"
                + "import java.util.concurrent.atomic.AtomicInteger;\n"
                + "public final class LocalJMeterValidationWorker {\n"
                + "  private static final long STARTUP_TIMEOUT_NANOS = TimeUnit.SECONDS.toNanos("
                + LocalJMeterWorkerClient.DEFAULT_STARTUP_TIMEOUT.getSeconds() + ");\n"
                + "  private static final AtomicInteger REQUESTS = new AtomicInteger();\n"
                + "  private static final Set<String> DESCRIPTORS = new HashSet<String>();\n"
                + "  private static boolean registryBuilt;\n"
                + "  private static boolean fingerprintPrewarmed;\n"
                + "  private static boolean childStarted;\n"
                + "  public static void main(String[] args) throws Exception {\n"
                + "    if (args.length == 2 && \"--child\".equals(args[0])) {\n"
                + "      Files.write(Paths.get(args[1]), currentPid().getBytes(StandardCharsets.UTF_8));\n"
                + "      Thread.sleep(TimeUnit.SECONDS.toMillis(30));\n"
                + "      return;\n"
                + "    }\n"
                + "    publishStartupProcessIds();\n"
                + "    System.out.println(\"JMX_AGENT_LOCAL_WORKER_READY\");\n"
                + "    System.out.flush();\n"
                + "    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in, StandardCharsets.UTF_8));\n"
                + "    String line;\n"
                + "    while ((line = reader.readLine()) != null) {\n"
                + "      startConfiguredChild(line);\n"
                + "      startLateOutput(line);\n"
                + "      startLateStderr(line);\n"
                + "      writeConfiguredWorkerPid(line);\n"
                + "      if (line.contains(\"hang-preflight\")) { Thread.sleep(TimeUnit.SECONDS.toMillis(30)); continue; }\n"
                + "      if (line.contains(\"slow-preflight\")) { Thread.sleep(500L); }\n"
                + "      recordFingerprintPrewarm(line);\n"
                + "      awaitLateOutputBeforePreflight(line);\n"
                + "      awaitLateStderrBeforePreflight(line);\n"
                + "      System.out.println(\"JMX_AGENT_LOCAL_WORKER_PREFLIGHT_READY:\" + jsonString(line, \"requestId\"));\n"
                + "      System.out.flush();\n"
                + "      recordRequest(line);\n"
                + "      recordRegistryBuild(line);\n"
                + "      coordinateConfiguredRequest(line);\n"
                + "      blockConfiguredWarmup(line);\n"
                + "      if (line.contains(\"descriptor-retry\")) {\n"
                + "        if (recordDescriptorBuild(line, false) == 1) {\n"
                + "          System.out.println(domainFailureResponse(line, REQUESTS.incrementAndGet()));\n"
                + "          System.out.flush();\n"
                + "          continue;\n"
                + "        }\n"
                + "        DESCRIPTORS.add(\"descriptor-retry\");\n"
                + "      } else {\n"
                + "        recordDescriptorBuild(line, true);\n"
                + "      }\n"
                + "      if (line.contains(\"hang-configure\")) {\n"
                + "        Thread.sleep(TimeUnit.SECONDS.toMillis(30));\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"slow-configure\")) {\n"
                + "        Thread.sleep(750L);\n"
                + "      }\n"
                + "      if (line.contains(\"malformed\")) {\n"
                + "        awaitConfiguredRelease(line);\n"
                + "        if (line.contains(\"noisy-malformed\")) {\n"
                + "          for (int index = 0; index < 10000; index++) {\n"
                + "            System.out.println(\"NOISY_MALFORMED_STDOUT_\" + index);\n"
                + "          }\n"
                + "        }\n"
                + "        System.out.println(\"{malformed-protocol-response\");\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      int count = REQUESTS.incrementAndGet();\n"
                + "      if (line.contains(\"catastrophic-worker-loss\")) {\n"
                + "        recordCatastrophicMutation(line);\n"
                + "        Runtime.getRuntime().halt(23);\n"
                + "      }\n"
                + "      if (line.contains(\"renderReadData\")) {\n"
                + "        String requestedRef = jsonString(line, \"readRef\");\n"
                + "        System.out.println(!requestedRef.isEmpty() && !requestedRef.equals(currentToken())\n"
                + "            ? unavailableRefResponse(line) : readResponse(line));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"applyPatch\") && jsonString(line, \"requestId\").isEmpty()) {\n"
                + "        System.out.println(successResponse(line, count, \"MISSING_WIRE_NONCE\").replace(\"\\\"requestId\\\":null\", \"\\\"requestId\\\":\\\"unexpected-nonce\\\"\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"dry-run-missing-response-nonce\")) {\n"
                + "        System.out.println(successResponse(line, count, \"MISSING_RESPONSE_NONCE\").replace(\"\\\"requestId\\\":\\\"\" + jsonString(line, \"requestId\") + \"\\\",\", \"\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"dry-run-mismatched-response-nonce\")) {\n"
                + "        System.out.println(successResponse(line, count, \"MISMATCHED_RESPONSE_NONCE\").replace(jsonString(line, \"requestId\"), \"foreign-request-id\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"foreign-response\")) {\n"
                + "        System.out.println(successResponse(line, count, \"FOREIGN\").replace(jsonString(line, \"requestId\"), \"foreign-request-id\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"missing-request-id\")) {\n"
                + "        System.out.println(successResponse(line, count, \"MISSING\").replace(\"\\\"requestId\\\":\\\"\" + jsonString(line, \"requestId\") + \"\\\",\", \"\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"mismatched-operation\")) {\n"
                + "        System.out.println(successResponse(line, count, \"MISMATCH\").replace(\"\\\"operation\\\":\\\"componentDetails\\\"\", \"\\\"operation\\\":\\\"loadJmx\\\"\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"contradictory-response\")) {\n"
                + "        System.out.println(successResponse(line, count, \"CONTRADICTORY\").replace(\"\\\"disposition\\\":\\\"SUCCESS\\\"\", \"\\\"disposition\\\":\\\"DOMAIN_FAILURE\\\"\"));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      if (line.contains(\"domain-failure\")) {\n"
                + "        System.out.println(domainFailureResponse(line, count));\n"
                + "        System.out.flush();\n"
                + "        continue;\n"
                + "      }\n"
                + "      String stdout = count == 1 ? \"FIRST_RESPONSE_STDOUT\" : \"SECOND_RESPONSE_STDOUT\";\n"
                + "      System.out.println(successResponse(line, count, stdout));\n"
                + "      if (count == 1) {\n"
                + "        System.out.println(\"FIRST_RESPONSE_TRAILING_STDOUT\");\n"
                + "      }\n"
                + "      System.out.flush();\n"
                + "      if (line.contains(\"exit-seven\")) {\n"
                + "        Runtime.getRuntime().halt(7);\n"
                + "      }\n"
                + "    }\n"
                + "  }\n"
                + "  private static void publishStartupProcessIds() throws Exception {\n"
                + "    Path propertiesPath = Paths.get(\"user.properties\");\n"
                + "    if (!Files.isRegularFile(propertiesPath)) return;\n"
                + "    Properties properties = new Properties();\n"
                + "    try (InputStream input = Files.newInputStream(propertiesPath)) { properties.load(input); }\n"
                + "    String childPid = properties.getProperty(\"j4a.fake.child.pid\", \"\");\n"
                + "    if (!childPid.isEmpty()) {\n"
                + "      childStarted = true;\n"
                + "      new ProcessBuilder(javaExecutable(), \"-Dj4a.worker.id=\" + System.getProperty(\"j4a.worker.id\", \"\"), \"-cp\", System.getProperty(\"java.class.path\"),\n"
                + "          LocalJMeterValidationWorker.class.getName(), \"--child\", childPid).start();\n"
                + "      awaitChildPid(Paths.get(childPid));\n"
                + "    }\n"
                + "    String workerPid = properties.getProperty(\"j4a.fake.worker.pid\", \"\");\n"
                + "    if (!workerPid.isEmpty()) Files.write(Paths.get(workerPid), currentPid().getBytes(StandardCharsets.UTF_8));\n"
                + "    String pidReady = properties.getProperty(\"j4a.fake.pid.ready\", \"\");\n"
                + "    if (!pidReady.isEmpty()) Files.write(Paths.get(pidReady), java.util.Collections.singletonList(\"ready\"), StandardCharsets.UTF_8);\n"
                + "  }\n"
                + "  private static void awaitConfiguredRelease(String line) throws Exception {\n"
                + "    if (!line.contains(\"blocked-malformed\")) return;\n"
                + "    String home = jsonString(line, \"jmeterHome\");\n"
                + "    Properties properties = new Properties();\n"
                + "    try (InputStream input = Files.newInputStream(Paths.get(home).resolve(\"bin\").resolve(\"user.properties\"))) { properties.load(input); }\n"
                + "    Path release = Paths.get(properties.getProperty(\"j4a.fake.release\"));\n"
                + "    long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);\n"
                + "    while (!Files.exists(release) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "  }\n"
                + "  private static void startLateOutput(final String line) throws Exception {\n"
                + "    if (!line.contains(\"late-output-first\")) return;\n"
                + "    Thread late = new Thread(() -> {\n"
                + "      try {\n"
                + "        Path release = configuredPath(line, \"j4a.fake.late.release\");\n"
                + "        Path written = configuredPath(line, \"j4a.fake.late.written\");\n"
                + "        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);\n"
                + "        while (release != null && !Files.exists(release) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "        if (release == null || !Files.exists(release)) return;\n"
                + "        for (int index = 0; index < 10000; index++) System.out.println(\"LATE_OLD_STDOUT_\" + index);\n"
                + "        System.out.flush();\n"
                + "        if (written != null) Files.write(written, java.util.Collections.singletonList(\"written\"), StandardCharsets.UTF_8);\n"
                + "      } catch (Exception ignored) { }\n"
                + "    }, \"late-old-stdout\");\n"
                + "    late.setDaemon(true);\n"
                + "    late.start();\n"
                + "  }\n"
                + "  private static void awaitLateOutputBeforePreflight(String line) throws Exception {\n"
                + "    if (!line.contains(\"late-next\")) return;\n"
                + "    Path entered = configuredPath(line, \"j4a.fake.late.next.entered\");\n"
                + "    Path written = configuredPath(line, \"j4a.fake.late.written\");\n"
                + "    if (entered != null) Files.write(entered, java.util.Collections.singletonList(\"entered\"), StandardCharsets.UTF_8);\n"
                + "    long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);\n"
                + "    while (written != null && !Files.exists(written) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "    if (written != null && !Files.exists(written)) throw new IllegalStateException(\"Late output did not arrive before preflight\");\n"
                + "  }\n"
                + "  private static void startLateStderr(final String line) throws Exception {\n"
                + "    if (!line.contains(\"late-stderr-first\")) return;\n"
                + "    Thread late = new Thread(() -> {\n"
                + "      try {\n"
                + "        Path release = configuredPath(line, \"j4a.fake.late.stderr.release\");\n"
                + "        Path written = configuredPath(line, \"j4a.fake.late.stderr.written\");\n"
                + "        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);\n"
                + "        while (release != null && !Files.exists(release) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "        if (release == null || !Files.exists(release)) return;\n"
                + "        for (int index = 0; index < 10000; index++) System.err.println(\"LATE_OLD_STDERR_\" + index);\n"
                + "        System.err.flush();\n"
                + "        if (written != null) Files.write(written, java.util.Collections.singletonList(\"written\"), StandardCharsets.UTF_8);\n"
                + "      } catch (Exception ignored) { }\n"
                + "    }, \"late-old-stderr\");\n"
                + "    late.setDaemon(true);\n"
                + "    late.start();\n"
                + "  }\n"
                + "  private static void awaitLateStderrBeforePreflight(String line) throws Exception {\n"
                + "    if (!line.contains(\"late-stderr-next\")) return;\n"
                + "    Path entered = configuredPath(line, \"j4a.fake.late.stderr.next.entered\");\n"
                + "    Path written = configuredPath(line, \"j4a.fake.late.stderr.written\");\n"
                + "    if (entered != null) Files.write(entered, java.util.Collections.singletonList(\"entered\"), StandardCharsets.UTF_8);\n"
                + "    long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);\n"
                + "    while (written != null && !Files.exists(written) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "    if (written != null && !Files.exists(written)) throw new IllegalStateException(\"Late stderr did not arrive before preflight\");\n"
                + "  }\n"
                + "  private static String successResponse(String line, int count, String stdout) {\n"
                + "    return responsePrefix(line)\n"
                + "        + \"\\\"success\\\":true,\\\"disposition\\\":\\\"SUCCESS\\\",\\\"message\\\":\\\"ok\\\",\\\"payload\\\":\\\"request-count: \" + count\n"
                + "        + \"; worker-pid: \" + currentPid() + \"\\\",\\\"stdout\\\":\\\"\" + stdout + \"\\\",\\\"stderr\\\":\\\"\\\"}\";\n"
                + "  }\n"
                + "  private static void recordCatastrophicMutation(String line) throws Exception {\n"
                + "    Path count = configuredPath(line, \"j4a.fake.mutation.execution.count\");\n"
                + "    if (count != null) Files.write(count, java.util.Collections.singletonList(\"execution\"),\n"
                + "        StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND);\n"
                + "    String target = jsonString(line, \"targetPath\");\n"
                + "    if (!target.isEmpty()) Files.write(Paths.get(target),\n"
                + "        \"CATASTROPHIC_MUTATION_COMMITTED\".getBytes(StandardCharsets.UTF_8));\n"
                + "  }\n"
                + "  private static String domainFailureResponse(String line, int count) {\n"
                + "    return responsePrefix(line)\n"
                + "        + \"\\\"success\\\":false,\\\"disposition\\\":\\\"DOMAIN_FAILURE\\\",\\\"errorCode\\\":\\\"COMPONENT_IDENTITY_NOT_FOUND\\\",\"\n"
                + "        + \"\\\"category\\\":\\\"operation\\\",\\\"message\\\":\\\"rejected\\\",\"\n"
                + "        + \"\\\"payload\\\":\\\"request-count: \" + count + \"; worker-pid: \" + currentPid()\n"
                + "        + \"\\\",\\\"stdout\\\":\\\"\\\",\\\"stderr\\\":\\\"\\\"}\";\n"
                + "  }\n"
                + "  private static String readResponse(String line) {\n"
                + "    return responsePrefix(line)\n"
                + "        + \"\\\"success\\\":true,\\\"disposition\\\":\\\"SUCCESS\\\",\\\"message\\\":\\\"ok\\\",\"\n"
                + "        + \"\\\"payload\\\":\\\"node:\\\\n  ref: \" + currentToken()\n"
                + "        + \"\\\",\\\"stdout\\\":\\\"\\\",\\\"stderr\\\":\\\"\\\"}\";\n"
                + "  }\n"
                + "  private static String unavailableRefResponse(String line) {\n"
                + "    return responsePrefix(line)\n"
                + "        + \"\\\"success\\\":false,\\\"disposition\\\":\\\"DOMAIN_FAILURE\\\",\"\n"
                + "        + \"\\\"errorCode\\\":\\\"MCP_REF_NOT_FOUND\\\",\\\"category\\\":\\\"usage\\\",\"\n"
                + "        + \"\\\"message\\\":\\\"stale generation ref\\\",\\\"payload\\\":\\\"\\\",\"\n"
                + "        + \"\\\"stdout\\\":\\\"\\\",\\\"stderr\\\":\\\"\\\"}\";\n"
                + "  }\n"
                + "  private static String currentToken() {\n"
                + "    return String.format(\"R%015d\", Long.parseLong(currentPid()));\n"
                + "  }\n"
                + "  private static String responsePrefix(String line) {\n"
                + "    return \"{\" + responseField(line, \"requestId\")\n"
                + "        + \",\" + responseField(line, \"operation\")\n"
                + "        + \",\" + responseField(line, \"jmxPath\")\n"
                + "        + \",\" + responseField(line, \"jmeterHome\")\n"
                + "        + \",\" + responseField(line, \"component\")\n"
                + "        + \",\" + responseField(line, \"patchPath\") + \",\";\n"
                + "  }\n"
                + "  private static String responseField(String line, String name) {\n"
                + "    return \"\\\"\" + name + \"\\\":\" + rawJsonValue(line, name);\n"
                + "  }\n"
                + "  private static String rawJsonValue(String line, String name) {\n"
                + "    String needle = \"\\\"\" + name + \"\\\":\";\n"
                + "    int start = line.indexOf(needle);\n"
                + "    if (start < 0) return \"null\";\n"
                + "    start += needle.length();\n"
                + "    if (line.charAt(start) != '\\\"') {\n"
                + "      int end = line.indexOf(',', start);\n"
                + "      if (end < 0) end = line.indexOf('}', start);\n"
                + "      return line.substring(start, end);\n"
                + "    }\n"
                + "    boolean escaped = false;\n"
                + "    for (int index = start + 1; index < line.length(); index++) {\n"
                + "      char current = line.charAt(index);\n"
                + "      if (escaped) escaped = false;\n"
                + "      else if (current == '\\\\') escaped = true;\n"
                + "      else if (current == '\\\"') return line.substring(start, index + 1);\n"
                + "    }\n"
                + "    throw new IllegalArgumentException(\"unterminated JSON string for \" + name);\n"
                + "  }\n"
                + "  private static void writeConfiguredWorkerPid(String line) throws Exception {\n"
                + "    String home = jsonString(line, \"jmeterHome\");\n"
                + "    if (home.isEmpty()) {\n"
                + "      return;\n"
                + "    }\n"
                + "    Path propertiesPath = Paths.get(home).resolve(\"bin\").resolve(\"user.properties\");\n"
                + "    if (!Files.isRegularFile(propertiesPath)) {\n"
                + "      return;\n"
                + "    }\n"
                + "    Properties properties = new Properties();\n"
                + "    try (InputStream input = Files.newInputStream(propertiesPath)) {\n"
                + "      properties.load(input);\n"
                + "    }\n"
                + "    String workerPid = properties.getProperty(\"j4a.fake.worker.pid\", \"\");\n"
                + "    if (!workerPid.isEmpty()) {\n"
                + "      Files.write(Paths.get(workerPid), currentPid().getBytes(StandardCharsets.UTF_8));\n"
                + "    }\n"
                + "  }\n"
                + "  private static void recordRequest(String line) throws Exception {\n"
                + "    String home = jsonString(line, \"jmeterHome\");\n"
                + "    if (home.isEmpty()) return;\n"
                + "    Path propertiesPath = Paths.get(home).resolve(\"bin\").resolve(\"user.properties\");\n"
                + "    if (!Files.isRegularFile(propertiesPath)) return;\n"
                + "    Properties properties = new Properties();\n"
                + "    try (InputStream input = Files.newInputStream(propertiesPath)) { properties.load(input); }\n"
                + "    String requestCount = properties.getProperty(\"j4a.fake.request.count\", \"\");\n"
                + "    if (!requestCount.isEmpty()) {\n"
                + "      Files.write(Paths.get(requestCount), java.util.Collections.singletonList(\"request\"),\n"
                + "          StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND);\n"
                + "    }\n"
                + "  }\n"
                + "  private static void recordRegistryBuild(String line) throws Exception {\n"
                + "    if (registryBuilt) return;\n"
                + "    registryBuilt = true;\n"
                + "    appendConfiguredCounter(line, \"j4a.fake.registry.build.count\");\n"
                + "  }\n"
                + "  private static void recordFingerprintPrewarm(String line) throws Exception {\n"
                + "    if (fingerprintPrewarmed) return;\n"
                + "    fingerprintPrewarmed = true;\n"
                + "    appendConfiguredCounter(line, \"j4a.fake.fingerprint.scan.count\");\n"
                + "  }\n"
                + "  private static void blockConfiguredWarmup(String line) throws Exception {\n"
                + "    if (!line.contains(\"discoverComponents\")) return;\n"
                + "    Path release = configuredPath(line, \"j4a.fake.warmup.release\");\n"
                + "    Path entered = configuredPath(line, \"j4a.fake.warmup.entered\");\n"
                + "    if (release == null || entered == null) return;\n"
                + "    Files.write(entered, java.util.Collections.singletonList(\"entered\"), StandardCharsets.UTF_8);\n"
                + "    long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(30);\n"
                + "    while (!Files.exists(release) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "  }\n"
                + "  private static void coordinateConfiguredRequest(String line) throws Exception {\n"
                + "    if (!line.contains(\"coordinated-configure\")) return;\n"
                + "    Path root = configuredPath(line, \"j4a.fake.coordination.root\");\n"
                + "    Path release = configuredPath(line, \"j4a.fake.coordination.release\");\n"
                + "    if (root == null || release == null) return;\n"
                + "    Path entered = root.resolve(\"entered\");\n"
                + "    Files.createDirectories(entered);\n"
                + "    Files.write(entered.resolve(jsonString(line, \"component\")),\n"
                + "        java.util.Collections.singletonList(\"entered\"), StandardCharsets.UTF_8);\n"
                + "    long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(30);\n"
                + "    while (!Files.exists(release) && System.nanoTime() < deadline) Thread.sleep(10L);\n"
                + "    if (!Files.exists(release)) throw new IllegalStateException(\"Coordination release was not published\");\n"
                + "  }\n"
                + "  private static int recordDescriptorBuild(String line, boolean successful) throws Exception {\n"
                + "    String component = jsonString(line, \"component\");\n"
                + "    if (component.isEmpty()) return 0;\n"
                + "    if (successful && DESCRIPTORS.contains(component)) return 0;\n"
                + "    appendConfiguredCounter(line, \"j4a.fake.descriptor.build.count\");\n"
                + "    if (successful) DESCRIPTORS.add(component);\n"
                + "    Path counter = configuredPath(line, \"j4a.fake.descriptor.build.count\");\n"
                + "    return counter == null ? 0 : Files.readAllLines(counter, StandardCharsets.UTF_8).size();\n"
                + "  }\n"
                + "  private static void appendConfiguredCounter(String line, String property) throws Exception {\n"
                + "    Path counter = configuredPath(line, property);\n"
                + "    if (counter != null) Files.write(counter, java.util.Collections.singletonList(\"build\"),\n"
                + "        StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND);\n"
                + "  }\n"
                + "  private static Path configuredPath(String line, String property) throws Exception {\n"
                + "    String home = jsonString(line, \"jmeterHome\");\n"
                + "    if (home.isEmpty()) return null;\n"
                + "    Path propertiesPath = Paths.get(home).resolve(\"bin\").resolve(\"user.properties\");\n"
                + "    if (!Files.isRegularFile(propertiesPath)) return null;\n"
                + "    Properties properties = new Properties();\n"
                + "    try (InputStream input = Files.newInputStream(propertiesPath)) { properties.load(input); }\n"
                + "    String value = properties.getProperty(property, \"\");\n"
                + "    return value.isEmpty() ? null : Paths.get(value);\n"
                + "  }\n"
                + "  private static void startConfiguredChild(String line) throws Exception {\n"
                + "    if (childStarted) {\n"
                + "      return;\n"
                + "    }\n"
                + "    String home = jsonString(line, \"jmeterHome\");\n"
                + "    if (home.isEmpty()) {\n"
                + "      return;\n"
                + "    }\n"
                + "    Path propertiesPath = Paths.get(home).resolve(\"bin\").resolve(\"user.properties\");\n"
                + "    if (!Files.isRegularFile(propertiesPath)) {\n"
                + "      return;\n"
                + "    }\n"
                + "    Properties properties = new Properties();\n"
                + "    try (InputStream input = Files.newInputStream(propertiesPath)) {\n"
                + "      properties.load(input);\n"
                + "    }\n"
                + "    String childPid = properties.getProperty(\"j4a.fake.child.pid\", \"\");\n"
                + "    if (childPid.isEmpty()) {\n"
                + "      return;\n"
                + "    }\n"
                + "    childStarted = true;\n"
                + "    new ProcessBuilder(javaExecutable(), \"-Dj4a.worker.id=\" + System.getProperty(\"j4a.worker.id\", \"\"), \"-cp\", System.getProperty(\"java.class.path\"),\n"
                + "        LocalJMeterValidationWorker.class.getName(), \"--child\", childPid).start();\n"
                + "    awaitChildPid(Paths.get(childPid));\n"
                + "  }\n"
                + "  private static void awaitChildPid(Path childPid) throws Exception {\n"
                + "    long deadline = System.nanoTime() + STARTUP_TIMEOUT_NANOS;\n"
                + "    while (System.nanoTime() < deadline) {\n"
                + "      if (Files.isRegularFile(childPid)) {\n"
                + "        String value = new String(Files.readAllBytes(childPid), StandardCharsets.UTF_8).trim();\n"
                + "        if (value.matches(\"[0-9]+\")) return;\n"
                + "      }\n"
                + "      Thread.sleep(10L);\n"
                + "    }\n"
                + "    throw new IllegalStateException(\"Timed out waiting for child PID publication: \" + childPid);\n"
                + "  }\n"
                + "  private static String jsonString(String line, String name) {\n"
                + "    String needle = \"\\\"\" + name + \"\\\":\\\"\";\n"
                + "    int start = line.indexOf(needle);\n"
                + "    if (start < 0) {\n"
                + "      return \"\";\n"
                + "    }\n"
                + "    StringBuilder value = new StringBuilder();\n"
                + "    boolean escaped = false;\n"
                + "    for (int index = start + needle.length(); index < line.length(); index++) {\n"
                + "      char current = line.charAt(index);\n"
                + "      if (escaped) {\n"
                + "        value.append(current);\n"
                + "        escaped = false;\n"
                + "      } else if (current == '\\\\') {\n"
                + "        escaped = true;\n"
                + "      } else if (current == '\\\"') {\n"
                + "        return value.toString();\n"
                + "      } else {\n"
                + "        value.append(current);\n"
                + "      }\n"
                + "    }\n"
                + "    return value.toString();\n"
                + "  }\n"
                + "  private static String javaExecutable() {\n"
                + "    String executable = System.getProperty(\"os.name\", \"\").toLowerCase().contains(\"win\") ? \"java.exe\" : \"java\";\n"
                + "    return Paths.get(System.getProperty(\"java.home\"), \"bin\", executable).toString();\n"
                + "  }\n"
                + "  private static String currentPid() {\n"
                + "    String runtimeName = ManagementFactory.getRuntimeMXBean().getName();\n"
                + "    int separator = runtimeName.indexOf('@');\n"
                + "    return separator >= 0 ? runtimeName.substring(0, separator) : runtimeName;\n"
                + "  }\n"
                + "}\n";
    }
}
